# Generated by Django 4.1.7 on 2023-03-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('MID', models.CharField(default='00000000', max_length=8)),
                ('DOI', models.CharField(default=datetime.date(2023, 3, 22), max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
