# Generated by Django 4.1.7 on 2023-03-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Client',
        ),
    ]
