# Generated by Django 4.1.7 on 2023-03-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0002_rename_student_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.AddField(
            model_name='client',
            name='DOI',
            field=models.CharField(default=datetime.date(2023, 3, 10), max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='ED',
            field=models.CharField(default=datetime.date(2023, 3, 10), max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='ID',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='plate',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
