# Generated by Django 4.1.7 on 2023-03-14 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0003_remove_client_age_remove_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ID',
        ),
        migrations.AddField(
            model_name='client',
            name='LID',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='DOI',
            field=models.CharField(default=datetime.date(2023, 3, 14), max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ED',
            field=models.CharField(default=datetime.date(2023, 3, 14), max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='plate',
            field=models.CharField(default='00', max_length=8),
        ),
    ]
