# Generated by Django 4.1.7 on 2023-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0004_remove_client_id_client_lid_alter_client_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plate',
            field=models.CharField(default='KAA 001A', max_length=8),
        ),
    ]
