# Generated by Django 4.1.7 on 2023-03-17 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0005_alter_client_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='LID',
            new_name='MID',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ED',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plate',
        ),
        migrations.AlterField(
            model_name='client',
            name='DOI',
            field=models.CharField(default=datetime.date(2023, 3, 17), max_length=20),
        ),
    ]
