# Generated by Django 4.1.7 on 2023-03-21 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sammydjango', '0006_rename_lid_client_mid_remove_client_ed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='DOI',
            field=models.CharField(default=datetime.date(2023, 3, 21), max_length=20),
        ),
    ]
